output: docs
clean: true
skip_undocumented: true
sdk: iphone
author: Ronan O Ciosoig
author_url: https://www.stanwood.io 
copyright: '© 2018 [Stanwood GmbH] (https://www.stanwood.io) under MIT license.'
readme: README.md
podspec: StanwoodAnalytics.podspec
github_url: https://github.com/stanwood/Stanwood_Analytics_iOS
min_acl: public
theme: fullwidth
custom_categories: 
  - name: Core
    children:
    - AlertFactory
    - DataStore
    - StanwoodAnalytics
    - Tracker
    - TrackerKeys
